### ISSUE TITLE
Make the repository fully reproducible!

### ISSUE THREAD

**Issue by jfy133** [aemann01/diet_calculus#1]
1. Use conda
2. Relative paths compared to a cloned version of this repository
3 ...

**Comment by aemann01** [comment]
Oooo I didn't know you could make your own conda environments, is that what you mean?

**Comment by jfy133** [comment]
Yes! "One I made earlier", as reference: https://github.com/jfy133/MEx-IPA/blob/master/environment.yml

To create
`conda env create -f environment.yaml`

Then `conda activate <env_name>` and all the defined programs in the `environment.yml` are in your path.

Gargammel isn't on bioconda yet, but doesn't look like it should be _too_ hard to add.

**Comment by aemann01** [comment]
Cool cool. I'll give it a try. Thanks James!
