### ISSUE TITLE
examples.ids not found

### ISSUE THREAD

**Issue by CamilaDuitama** [aemann01/diet_calculus#6]
Hi!
I am trying to replicate your pipeline (specifically 03-synthetic_dataset_generation and 04-synthetic_real_dataset_processing) and I can't find the file `examples.ids`, where exactly could I find it ?
Thanks,
Camila

**Comment by aemann01** [comment]
File is now uploaded to the 03-synthetic_dataset_generation directory!

**Comment by CamilaDuitama** [comment]
Thanks!
